development:
  host: mysql
  adapter: mysql2
  encoding: utf8
  pool: 5

  username: rails
  database: iv_schools
  password: qwerty

production:
  host: mysql
  adapter: mysql2
  encoding: utf8
  pool: 5

  username: rails
  database: iv_schools
  password: qwerty
